In [37]:
#Imports
import pandas as pd

#Load data
file_path = '/Users/srujanpothina/Desktop/ecommerce-sales-analysis-global-superstore/Data/Raw/Global Superstore.xls'

# Some versions of the dataset have multiple sheets (Orders, Returns, etc.)
xls = pd.ExcelFile(file_path)
xls.sheet_names

['Orders', 'Returns', 'People']

In [38]:
orders_df = pd.read_excel(file_path, sheet_name="Orders")
returns_df = pd.read_excel(file_path, sheet_name="Returns")
people_df = pd.read_excel(file_path, sheet_name="People")

In [39]:
orders_df.describe(include="all")

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
count,51290.00000,51290,51290,51290,51290,51290,51290,51290,51290,51290,...,51290,51290,51290,51290,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290
unique,NaN,25035,NaN,NaN,4,1590,795,3,3636,1094,...,10292,3,17,3788,NaN,NaN,NaN,NaN,NaN,4
top,NaN,CA-2014-100111,NaN,NaN,Standard Class,PO-18850,Muhammed Yedwab,Consumer,New York City,California,...,OFF-AR-10003651,Office Supplies,Binders,Staples,NaN,NaN,NaN,NaN,NaN,Medium
freq,NaN,14,NaN,NaN,30775,97,108,26518,915,2001,...,35,31273,6152,227,NaN,NaN,NaN,NaN,NaN,29433
mean,25645.50000,NaN,2013-05-11 21:26:49.155781120,2013-05-15 20:42:42.745174528,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,246.490581,3.476545,0.142908,28.610982,26.375818,NaN
min,1.00000,NaN,2011-01-01 00:00:00,2011-01-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.444000,1.000000,0.000000,-6599.978000,0.002000,NaN
25%,12823.25000,NaN,2012-06-19 00:00:00,2012-06-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,30.758625,2.000000,0.000000,0.000000,2.610000,NaN
50%,25645.50000,NaN,2013-07-08 00:00:00,2013-07-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,85.053000,3.000000,0.000000,9.240000,7.790000,NaN
75%,38467.75000,NaN,2014-05-22 00:00:00,2014-05-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,251.053200,5.000000,0.200000,36.810000,24.450000,NaN
max,51290.00000,NaN,2014-12-31 00:00:00,2015-01-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,22638.480000,14.000000,0.850000,8399.976000,933.570000,NaN
std,14806.29199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,487.565361,2.278766,0.212280,174.340972,57.296810,NaN

In [40]:
orders_df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [41]:
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  datetime64[ns]
 3   Ship Date       51290 non-null  datetime64[ns]
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(15)
memory usage: 9.4+ MB

In [42]:
orders_df.sample(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
4226,27070,IN-2011-51271,2011-10-06,2011-10-10,Standard Class,EH-13990,Erica Hackney,Consumer,Pune,Maharashtra,...,TEC-PH-10003348,Technology,Phones,"Cisco Speaker Phone, with Caller ID",415.440,3,0.0,170.280,76.710,High
18098,17635,IT-2013-1941593,2013-09-12,2013-09-15,Second Class,DB-13120,David Bremer,Corporate,Bergen op Zoom,North Brabant,...,OFF-SU-10001690,Office Supplies,Supplies,"Kleencut Box Cutter, Steel",136.200,8,0.5,-92.760,14.810,High
38149,15087,ES-2014-5022243,2014-07-01,2014-07-04,First Class,CD-12280,Christina DeMoss,Consumer,Wels,Upper Austria,...,OFF-EN-10000890,Office Supplies,Envelopes,"Ames Peel and Seal, Recycled",122.430,7,0.0,42.840,2.690,Medium
26187,17079,ES-2011-4450646,2011-11-30,2011-12-01,First Class,VB-21745,Victoria Brennan,Corporate,Paris,Ile-de-France,...,OFF-BI-10001723,Office Supplies,Binders,"Avery Binder, Clear",61.800,5,0.0,6.150,7.470,High
15545,2311,MX-2011-143364,2011-06-17,2011-06-22,Standard Class,SW-20755,Steven Ward,Corporate,Guantánamo,Guantánamo,...,OFF-BI-10004632,Office Supplies,Binders,"Avery 3-Hole Punch, Recycled",131.740,7,0.0,10.500,18.739,High
15740,7518,MX-2012-137918,2012-09-04,2012-09-10,Standard Class,CD-12280,Christina DeMoss,Consumer,Santa Cruz do Sul,Rio Grande do Sul,...,FUR-CH-10000430,Furniture,Chairs,"SAFCO Rocking Chair, Set of Two",274.320,3,0.0,79.500,18.412,Low
47268,15633,IT-2012-1204965,2012-01-19,2012-01-23,Standard Class,TS-21610,Troy Staebel,Consumer,Amsterdam,North Holland,...,OFF-FA-10000154,Office Supplies,Fasteners,"OIC Paper Clips, Bulk Pack",21.645,3,0.5,-0.495,0.850,Medium
6875,4366,MX-2014-165386,2014-08-28,2014-08-31,Second Class,LB-16795,Laurel Beltran,Home Office,San Salvador,San Salvador,...,FUR-CH-10003559,Furniture,Chairs,"Office Star Chairmat, Black",211.300,5,0.0,105.600,49.740,Critical
39814,7077,MX-2013-126207,2013-02-09,2013-02-14,Second Class,KD-16615,Ken Dana,Corporate,Santo Domingo,Santo Domingo,...,OFF-FA-10000563,Office Supplies,Fasteners,"Accos Push Pins, Assorted Sizes",19.152,3,0.2,5.472,2.289,Medium
41158,15517,ES-2013-3932669,2013-11-13,2013-11-19,Standard Class,EM-13810,Eleni McCrary,Corporate,Solingen,North Rhine-Westphalia,...,OFF-SU-10001351,Office Supplies,Supplies,"Stiletto Letter Opener, Steel",75.240,3,0.0,9.000,1.990,Medium

In [43]:
orders_df.head()     # first 5 rows

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [44]:
orders_df.tail()     # last 5

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
51285,29002,IN-2014-62366,2014-06-19,2014-06-19,Same Day,KE-16420,Katrina Edelman,Corporate,Kure,Hiroshima,...,OFF-FA-10000746,Office Supplies,Fasteners,"Advantus Thumb Tacks, 12 Pack",65.100,5,0.0,4.5000,0.010,Medium
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,OFF-AP-10002906,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,0.444,1,0.8,-1.1100,0.010,Medium
51287,40470,US-2013-155768,2013-12-02,2013-12-02,Same Day,LB-16795,Laurel Beltran,Home Office,Oxnard,California,...,OFF-EN-10001219,Office Supplies,Envelopes,"#10- 4 1/8"" x 9 1/2"" Security-Tint Envelopes",22.920,3,0.0,11.2308,0.010,High
51288,9596,MX-2012-140767,2012-02-18,2012-02-22,Standard Class,RB-19795,Ross Baird,Home Office,Valinhos,São Paulo,...,OFF-BI-10000806,Office Supplies,Binders,"Acco Index Tab, Economy",13.440,2,0.0,2.4000,0.003,Medium
51289,6147,MX-2012-134460,2012-05-22,2012-05-26,Second Class,MC-18100,Mick Crebagga,Consumer,Tipitapa,Managua,...,OFF-PA-10004155,Office Supplies,Paper,"Eaton Computer Printout Paper, 8.5 x 11",61.380,3,0.0,1.8000,0.002,High

In [45]:
orders_df.shape      # rows, columns

(51290, 24)

In [46]:
orders_df.isna().sum().sort_values(ascending=False)

Postal Code       41296
Row ID                0
Region                0
Shipping Cost         0
Profit                0
Discount              0
Quantity              0
Sales                 0
Product Name          0
Sub-Category          0
Category              0
Product ID            0
Market                0
Order ID              0
Country               0
State                 0
City                  0
Segment               0
Customer Name         0
Customer ID           0
Ship Mode             0
Ship Date             0
Order Date            0
Order Priority        0
dtype: int64

In [47]:
orders_df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
City                      object
State                     object
Country                   object
Postal Code              float64
Market                    object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

# Global Superstore – Data Overview

## Business Questions (Draft)

1. How are **sales and profit trending over time** (yearly, monthly)?
2. Which **regions and countries** generate the most revenue and profit?
3. Which **product categories and sub-categories** are most and least profitable?
4. Who are the **top customers** (by revenue and profit)?
5. What percentage of orders/customers are **repeat customers**?
6. How long does it typically take from **Order Date to Ship Date**?
7. Are there **unprofitable products** or regions that need attention?
8. How do **returns** impact overall performance?